// Code generated by mockery v1.0.0. DO NOT EDIT.

package ratelimiter

import mock "github.com/stretchr/testify/mock"

// MockRateLimiter is an autogenerated mock type for the RateLimiter type
type MockRateLimiter struct {
	mock.Mock
}

// Add provides a mock function with given fields: ipAddr
func (_m *MockRateLimiter) Add(ipAddr string) (int64, error) {
	ret := _m.Called(ipAddr)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(ipAddr)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ipAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMaxRate provides a mock function with given fields:
func (_m *MockRateLimiter) GetMaxRate() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
